/*
 * NameEntryPanel.java
 *
 * Copyright 2007 Sun Microsystems, Inc. ALL RIGHTS RESERVED Use of 
 * this software is authorized pursuant to the terms of the license 
 * found at http://developers.sun.com/berkeley_license.html.
 * 
 */

package ca.sixs;
/**
*
* @author John O'Conner (John.OConner@sun.com)
* modified by @author Rgr
*/


import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

import org.jdesktop.application.ApplicationContext;
import org.jdesktop.application.Resource;
import org.jdesktop.application.ResourceMap;


public class NameEntryPanel extends javax.swing.JPanel {
    
    @Resource
    String greetingMsg;
    
    /** Creates new form NameEntryPanel */
    public NameEntryPanel(ApplicationContext ctxt) {
        initComponents();
        ResourceMap resource = ctxt.getResourceMap(NameEntryPanel.class);
        resource.injectFields(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblNamePrompt = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnGreet = new javax.swing.JButton();

        lblNamePrompt.setText("jLabel1");
        lblNamePrompt.setName("lblNamePrompt");

        btnGreet.setText("jButton1");
        btnGreet.setName("btnGreet");
        btnGreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreetActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(layout.getLayoutStyle(Alignment.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(lblNamePrompt)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(txtName, GroupLayout.DEFAULT_SIZED, 305, Short.MAX_VALUE))
//                    .add(btnGreet))
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                    .add(lblNamePrompt)
//                    .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(btnGreet)
//                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreetActionPerformed
        String personalMsg = String.format(greetingMsg, txtName.getText());
        JOptionPane.showMessageDialog(this, personalMsg);
            
    }//GEN-LAST:event_btnGreetActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGreet;
    private javax.swing.JLabel lblNamePrompt;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    
}
