/*
 * ResizeFontPanel.java
 *
 * Copyright 2007 Sun Microsystems, Inc. ALL RIGHTS RESERVED Use of 
 * this software is authorized pursuant to the terms of the license 
 * found at http://developers.sun.com/berkeley_license.html.
 * 
 */

package ca.sixs;
/**
*
* @author John O'Conner (John.OConner@sun.com)
* modified by @author Rgr
*/


import java.awt.Font;

import javax.swing.ActionMap;
import javax.swing.GroupLayout;

import org.jdesktop.application.Action;
import org.jdesktop.application.ApplicationContext;
import org.jdesktop.application.ResourceMap;

@SuppressWarnings("serial")
public class ResizeFontPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ResizeFontPanel
     */
    public ResizeFontPanel(ApplicationContext ctxt) {
        initComponents();
    
        txtArea.setName("txtArea");
        ResourceMap resource = ctxt.getResourceMap(ResizeFontPanel.class);
        resource.injectComponents(this);
        ActionMap map = ctxt.getActionMap(this);
        
        btnMakeLarger.setAction(map.get("makeLarger"));
        btnMakeSmaller.setAction(map.get("makeSmaller"));
    }
    
    @Action
    public void makeLarger() {
        Font f = txtArea.getFont();
        int size = f.getSize();
        if (size < MAX_FONT_SIZE) {
            size++;
            f = new Font(f.getFontName(), f.getStyle(), size);
            txtArea.setFont(f);
        }
    }
    
    @Action
    public void makeSmaller() {
        Font f = txtArea.getFont();
        int size = f.getSize();
        if (size > MIN_FONT_SIZE) {
            size--;
            f = new Font(f.getFontName(), f.getStyle(), size);
            txtArea.setFont(f);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnMakeLarger = new javax.swing.JButton();
        btnMakeSmaller = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        btnMakeLarger.setText("jButton1");

        btnMakeSmaller.setText("jButton2");

        txtArea.setColumns(20);
        txtArea.setEditable(false);
        txtArea.setFont(new java.awt.Font("Arial", 0, 12));
        txtArea.setLineWrap(true);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
        		layout.createParallelGroup(GroupLayout.Alignment.LEADING).
        		addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        		layout.createParallelGroup(GroupLayout.Alignment.LEADING).
        		addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );
        		
        
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                    .add(btnMakeLarger)
//                    .add(btnMakeSmaller))
//                .addPreferredGap(GroupLayout.Alignment.TRAILING)
//                .add(jScrollPane1, GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .addContainerGap()
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
//                    .add(layout.createSequentialGroup()
//                        .add(btnMakeLarger)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(btnMakeSmaller)))
//                .addContainerGap())
//        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeLarger;
    private javax.swing.JButton btnMakeSmaller;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
    
    private static final int MAX_FONT_SIZE=22;
    private static final int MIN_FONT_SIZE=6;
}
